add_executable(fastregex_public_smoke public_smoke.cpp)
target_link_libraries(fastregex_public_smoke PRIVATE fastregex::fastregex)
set_target_properties(fastregex_public_smoke PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED YES)
add_test(NAME fastregex.public_smoke COMMAND fastregex_public_smoke)

add_executable(fastregex_compiler_smoke compiler_smoke.cpp)
target_link_libraries(fastregex_compiler_smoke PRIVATE fastregex_compiler)
add_test(NAME fastregex.compiler_smoke COMMAND fastregex_compiler_smoke)

add_executable(fastregex_parser_tests parser.cpp)
target_link_libraries(fastregex_parser_tests PRIVATE fastregex_compiler)
add_test(NAME fastregex.parser COMMAND fastregex_parser_tests)

add_executable(fastregex_nfa_tests nfa.cpp)
target_link_libraries(fastregex_nfa_tests PRIVATE fastregex_compiler)
add_test(NAME fastregex.nfa COMMAND fastregex_nfa_tests)

add_executable(fastregex_dfa_tests dfa.cpp)
target_link_libraries(fastregex_dfa_tests PRIVATE fastregex_compiler)
add_test(NAME fastregex.dfa COMMAND fastregex_dfa_tests)

add_executable(fastregex_dfa_match_tests dfa_match.cpp)
target_link_libraries(fastregex_dfa_match_tests PRIVATE fastregex_compiler)
add_test(NAME fastregex.dfa_match COMMAND fastregex_dfa_match_tests)
